
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld.fullname" . }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helloworld.selectorLabels" . | nindent 4 }}
    {{- if and (eq .Values.environment "prod") .Values.rollout.enabled }}
    version: stable
    {{- end }}

{{- if and (eq .Values.environment "prod") .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld.fullname" . }}-canary
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
    role: canary
spec:
  type: ClusterIP
  selector:
    {{- include "helloworld.selectorLabels" . | nindent 4 }}
    version: canary
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
{{- end }}