apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "helloworld.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
spec:
  gateways:
  - istio-system/ingressgateway
  hosts:
  - '*'
  http:
  - match:
    - sourceLabels:
        app: istio-ingressgateway
        istio: ingressgateway
      uri:
        prefix: /hello
    name: helloworld
    route:
    - destination:
         host: {{ include "helloworld.fullname" . }}.{{ .Values.namespace | default "default" }}.svc.cluster.local
        port:
          number: 5000
      weight: {{ .Values.traffic.canaryWeight }}
    - destination:
        host: {{ include "helloworld.fullname" . }}-canary.{{ .Values.namespace | default "default" }}.svc.cluster.local
        port:
          number: 5000
      weight: 0