apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "helloworld.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  gateways:
  - {{ include "helloworld.fullname" . }}-gateway
  hosts:
  - '*'
  http:
  - name: helloworld
    match:
    - uri:
        prefix: /hello
    route:
    - destination:
        host: {{ include "helloworld.fullname" . }}.{{ .Values.namespace | default .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port | default 5000 }}
      weight: 100
    - destination:
        host: {{ include "helloworld.fullname" . }}-canary.{{ .Values.namespace | default .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port | default 5000 }}
      weight: 0