{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    name: {{ .Values.namespace | default .Release.Namespace }}
    istio-injection: enabled
{{- end }}