{{- if and (eq .Values.environment "prod") .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "helloworld.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helloworld.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helloworld.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "helloworld.serviceAccountName" . }}
      containers:
      - name: {{ include "helloworld.appName" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
  strategy:
    canary:
      stableService: {{ include "helloworld.fullname" . }}
      canaryService: {{ include "helloworld.fullname" . }}-canary
      trafficRouting:
        istio:
          virtualService:
            name: {{ include "helloworld.fullname" . }}
            routes:
            - helloworld
      steps:
      - setWeight: 20
      - pause: {duration: 20s}
      - setWeight: 40
      - pause: {duration: 20s}
      - setWeight: 60
      - pause: {duration: 20s}
      - setWeight: 80
      - pause: {duration: 20s}
{{- end }}