{{- if and (eq .Values.environment "prod") .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "helloworld.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helloworld.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helloworld.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "helloworld.serviceAccountName" . }}
      containers:
      - name: {{ include "helloworld.appName" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
  strategy:
    canary:
      stableService: {{ include "helloworld.fullname" . }}          # 稳定 Service (已有)
      canaryService: {{ include "helloworld.fullname" . }}-canary   # 新建的 canary Service
      trafficRouting:
        istio:
          virtualService:
            name: {{ include "helloworld.fullname" . }}
            routes:
            - helloworld
          destinationRule:
            name: {{ include "helloworld.fullname" . }}
            stableSubsetName: stable
            canarySubsetName: canary
      stableMetadata:
        labels:
          version: stable
      canaryMetadata:
        labels:
          version: canary
      steps:
      - setWeight: 20
      - pause: { duration: 30s }
      - setWeight: 50
      - pause: { duration: 60s }
{{- end }}